version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: ${PROJECT_NAME}-postgres
    volumes:
      - ./conf/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
       - 5432:5432
  webserver:
    image: nginx:latest
    container_name: ${PROJECT_NAME}-webserver
    working_dir: /app
    volumes:
      - ./app:/app
      - ./conf/nginx:/etc/nginx/conf.d
    ports:
      - 8000:80
  php-fpm:
    build: conf/php-fpm
    container_name: ${PROJECT_NAME}-php-fpm
    working_dir: /app
    volumes:
    - ./app:/app
